version: '3.8'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 23102002Papa
            POSTGRES_DB: db_labs
        ports:
            - 5432:5432
        networks:
            - default

    app:
        build: ./app/
        depends_on:
            - db
        volumes:
            - ./app:/usr/src/app
        networks:
            - default

networks:
    default:
        name: lnet
